# Generated by Django 5.2.17 on 2026-09-11 12:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("local_date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("CLOSED", "Closed"), ("REPLACEMENT", "Replacement")],
                        max_length=16,
                    ),
                ),
                ("starts_at", models.TimeField(blank=True, null=True)),
                ("ends_at", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_exceptions",
                        to="catalog.barber",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_exceptions",
                        to="catalog.branch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "barber", "local_date"),
                        name="schedule_exception_branch_barber_date_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ends_at__isnull", True),
                                ("kind", "CLOSED"),
                                ("starts_at__isnull", True),
                            ),
                            models.Q(
                                ("ends_at__isnull", False),
                                ("kind", "REPLACEMENT"),
                                ("starts_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="schedule_exception_kind_times_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_rules",
                        to="catalog.barber",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_rules",
                        to="catalog.branch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "barber", "weekday", "starts_at", "ends_at"),
                        name="schedule_rule_branch_barber_slot_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="schedule_rule_weekday_valid",
                    ),
                ],
            },
        ),
    ]
