# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("booking", "0003_remove_booking_booking_buffers_nonnegative_and_more"),
        ("identity", "0002_owner_null_branch_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingManagementToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("guest_session_key", models.CharField(max_length=64)),
                ("encrypted_token", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=models.PROTECT,
                        related_name="management_token",
                        to="booking.booking",
                    ),
                ),
            ],
        ),
    ]
