# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [("identity", "0003_booking_management_token")]

    operations = [
        migrations.CreateModel(
            name="ApiRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope_digest", models.CharField(max_length=64)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_digest", "window_start"),
                        name="identity_rate_limit_scope_window_unique",
                    )
                ]
            },
        ),
    ]
