# Generated by Django 5.2.17 on 2026-09-11 13:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

CREATE_IMMUTABILITY_TRIGGERS_SQL = """
CREATE FUNCTION journal_reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'journal rows are append-only' USING ERRCODE = '55000';
END;
$$;
CREATE TRIGGER journal_audit_entry_immutable
BEFORE UPDATE OR DELETE ON journal_auditentry
FOR EACH ROW EXECUTE FUNCTION journal_reject_mutation();
CREATE TRIGGER journal_outbox_event_immutable
BEFORE UPDATE OR DELETE ON journal_outboxevent
FOR EACH ROW EXECUTE FUNCTION journal_reject_mutation();
"""

DROP_IMMUTABILITY_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS journal_audit_entry_immutable ON journal_auditentry;
DROP TRIGGER IF EXISTS journal_outbox_event_immutable ON journal_outboxevent;
DROP FUNCTION IF EXISTS journal_reject_mutation();
"""


class Migration(migrations.Migration):  # type: ignore[misc]
    initial = True

    dependencies = [
        ("booking", "0003_remove_booking_booking_buffers_nonnegative_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "booking_version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("operation", models.CharField(max_length=64)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("INTEGRATION", "Integration"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=64)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("correlation_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="booking.booking",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "booking_version"),
                        name="journal_audit_booking_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("booking_version__gte", 1)),
                        name="journal_audit_booking_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "booking_version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("event_kind", models.CharField(max_length=64)),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="booking.booking",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "booking_version", "event_kind"),
                        name="journal_outbox_booking_version_kind_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("booking_version__gte", 1)),
                        name="journal_outbox_booking_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__gte", 1)),
                        name="journal_outbox_schema_version_positive",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=CREATE_IMMUTABILITY_TRIGGERS_SQL,
            reverse_sql=DROP_IMMUTABILITY_TRIGGERS_SQL,
        ),
    ]
