# Generated by Django 5.2.17 on 2026-09-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("destination", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DELIVERED", "Delivered"),
                            ("PARKED", "Parked"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("owner_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="journal.outboxevent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "destination"),
                        name="journal_delivery_event_destination_unique",
                    )
                ],
            },
        ),
    ]
