# Generated by Django 5.2.17 on 2026-09-11 14:02

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="CommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "scope digest must be SHA-256"
                            )
                        ],
                    ),
                ),
                ("operation", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "fingerprint_version",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "fingerprint must be SHA-256"
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("TOMBSTONE", "Tombstone"),
                        ],
                        max_length=16,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=64)),
                ("response", models.JSONField(blank=True, null=True)),
                ("response_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_digest", "operation", "idempotency_key"),
                        name="idempotency_scope_operation_key_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fingerprint_version__gte", 1)),
                        name="idempotency_fingerprint_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["PROCESSING", "COMPLETED", "TOMBSTONE"])),
                        name="idempotency_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", False),
                                ("response__isnull", False),
                                ("response_expires_at__isnull", False),
                                ("state", "COMPLETED"),
                            ),
                            models.Q(
                                ("response__isnull", True),
                                ("state__in", ["PROCESSING", "TOMBSTONE"]),
                            ),
                            _connector="OR",
                        ),
                        name="idempotency_state_result_consistent",
                    ),
                ],
            },
        ),
    ]
