# Generated by Django 5.2.17 on 2026-09-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [("idempotency", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PrivacyRedaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(default="RESPONSE_RETENTION_EXPIRED", max_length=64)),
                ("redacted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redaction",
                        to="idempotency.commandreceipt",
                    ),
                ),
            ],
        )
    ]
