# Generated by Django 5.2.17 on 2026-09-11 12:53

import uuid
from decimal import Decimal

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

CREATE_RANGE_TRIGGER_SQL = """
CREATE FUNCTION booking_sync_occupied_range() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.occupied_range = tstzrange(
        NEW.start_at - make_interval(secs => NEW.buffer_before_seconds),
        NEW.end_at + make_interval(secs => NEW.buffer_after_seconds),
        '[)'
    );
    RETURN NEW;
END;
$$;
CREATE TRIGGER booking_sync_occupied_range_trigger
BEFORE INSERT OR UPDATE OF start_at, end_at, buffer_before_seconds,
    buffer_after_seconds, occupied_range ON booking_booking
FOR EACH ROW EXECUTE FUNCTION booking_sync_occupied_range();
"""

DROP_RANGE_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS booking_sync_occupied_range_trigger ON booking_booking;
DROP FUNCTION IF EXISTS booking_sync_occupied_range();
"""


class Migration(migrations.Migration):  # type: ignore[misc]
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No show"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("service_name", models.CharField(max_length=200)),
                (
                    "service_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "currency must be an ISO-like uppercase code"
                            )
                        ],
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("buffer_before_seconds", models.PositiveIntegerField(default=0)),
                ("buffer_after_seconds", models.PositiveIntegerField(default=0)),
                ("branch_timezone", models.CharField(max_length=64)),
                (
                    "occupied_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(editable=False),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.barber",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.branch",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.serviceoffering",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)), name="booking_version_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="booking_service_interval_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_seconds__gt", 0)),
                        name="booking_duration_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("service_price__gte", 0)),
                        name="booking_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("buffer_before_seconds__gte", 0), ("buffer_after_seconds__gte", 0)
                        ),
                        name="booking_buffers_nonnegative",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status", "CANCELLED"), _negated=True),
                        expressions=[("barber", "="), ("occupied_range", "&&")],
                        name="booking_barber_occupied_range_excludes_overlap",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=CREATE_RANGE_TRIGGER_SQL,
            reverse_sql=DROP_RANGE_TRIGGER_SQL,
        ),
    ]
