# Generated by Django 5.2.17 on 2026-09-11 12:53

import django.db.models.expressions
from django.db import migrations, models

import barbershop.booking.models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("booking", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "end_at",
                        django.db.models.expressions.CombinedExpression(
                            models.F("start_at"),
                            "+",
                            barbershop.booking.models.SecondsInterval(models.F("duration_seconds")),
                        ),
                    )
                ),
                name="booking_service_interval_matches_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMED", "CANCELLED", "COMPLETED", "NO_SHOW"])
                ),
                name="booking_status_valid",
            ),
        ),
    ]
