# Generated by Django 5.2.17 on 2026-09-11 13:06

from django.db import migrations

DROP_RANGE_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS booking_sync_occupied_range_trigger ON booking_booking;
"""

CREATE_RANGE_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION booking_sync_occupied_range() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.occupied_range = tstzrange(NEW.start_at, NEW.end_at, '[)');
    RETURN NEW;
END;
$$;
CREATE TRIGGER booking_sync_occupied_range_trigger
BEFORE INSERT OR UPDATE OF start_at, end_at, occupied_range ON booking_booking
FOR EACH ROW EXECUTE FUNCTION booking_sync_occupied_range();
"""

RESTORE_BUFFER_RANGE_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION booking_sync_occupied_range() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.occupied_range = tstzrange(
        NEW.start_at - make_interval(secs => NEW.buffer_before_seconds),
        NEW.end_at + make_interval(secs => NEW.buffer_after_seconds),
        '[)'
    );
    RETURN NEW;
END;
$$;
CREATE TRIGGER booking_sync_occupied_range_trigger
BEFORE INSERT OR UPDATE OF start_at, end_at, buffer_before_seconds,
    buffer_after_seconds, occupied_range ON booking_booking
FOR EACH ROW EXECUTE FUNCTION booking_sync_occupied_range();
"""


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("booking", "0002_booking_booking_service_interval_matches_duration_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DROP_RANGE_TRIGGER_SQL,
            reverse_sql=RESTORE_BUFFER_RANGE_TRIGGER_SQL,
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_buffers_nonnegative",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="buffer_after_seconds",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="buffer_before_seconds",
        ),
        migrations.RunSQL(
            sql=CREATE_RANGE_TRIGGER_SQL,
            reverse_sql=DROP_RANGE_TRIGGER_SQL,
        ),
    ]
