# Generated by Django 5.2.17 on 2026-09-11 13:06

from django.db import migrations


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="serviceoffering",
            name="catalog_service_buffers_nonnegative",
        ),
        migrations.RemoveField(
            model_name="serviceoffering",
            name="buffer_after_seconds",
        ),
        migrations.RemoveField(
            model_name="serviceoffering",
            name="buffer_before_seconds",
        ),
    ]
